# Generated by Django 5.0.14 on 2025-08-06 19:06
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_comments_comment_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
